/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "36331-ac0.asn"
 * 	`asn1c -fcompound-names -gen-PER`
 */

#ifndef	_Sib_TypeAndInfo_H_
#define	_Sib_TypeAndInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SystemInformationBlockType2.h"
#include "SystemInformationBlockType3.h"
#include "SystemInformationBlockType4.h"
#include "SystemInformationBlockType5.h"
#include "SystemInformationBlockType6.h"
#include "SystemInformationBlockType7.h"
#include "SystemInformationBlockType8.h"
#include "SystemInformationBlockType9.h"
#include "SystemInformationBlockType10.h"
#include "SystemInformationBlockType11.h"
#include "SystemInformationBlockType12-r9.h"
#include "SystemInformationBlockType13-r9.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Sib_TypeAndInfo_PR {
	Sib_TypeAndInfo_PR_NOTHING,	/* No components present */
	Sib_TypeAndInfo_PR_sib2,
	Sib_TypeAndInfo_PR_sib3,
	Sib_TypeAndInfo_PR_sib4,
	Sib_TypeAndInfo_PR_sib5,
	Sib_TypeAndInfo_PR_sib6,
	Sib_TypeAndInfo_PR_sib7,
	Sib_TypeAndInfo_PR_sib8,
	Sib_TypeAndInfo_PR_sib9,
	Sib_TypeAndInfo_PR_sib10,
	Sib_TypeAndInfo_PR_sib11,
	/* Extensions may appear below */
	Sib_TypeAndInfo_PR_sib12_v920,
	Sib_TypeAndInfo_PR_sib13_v920
} Sib_TypeAndInfo_PR;

/* Sib-TypeAndInfo */
typedef struct Sib_TypeAndInfo {
	Sib_TypeAndInfo_PR present;
	union Sib_TypeAndInfo_u {
		SystemInformationBlockType2_t	 sib2;
		SystemInformationBlockType3_t	 sib3;
		SystemInformationBlockType4_t	 sib4;
		SystemInformationBlockType5_t	 sib5;
		SystemInformationBlockType6_t	 sib6;
		SystemInformationBlockType7_t	 sib7;
		SystemInformationBlockType8_t	 sib8;
		SystemInformationBlockType9_t	 sib9;
		SystemInformationBlockType10_t	 sib10;
		SystemInformationBlockType11_t	 sib11;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
		SystemInformationBlockType12_r9_t	 sib12_v920;
		SystemInformationBlockType13_r9_t	 sib13_v920;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Sib_TypeAndInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Sib_TypeAndInfo;

#ifdef __cplusplus
}
#endif

#endif	/* _Sib_TypeAndInfo_H_ */
#include <asn_internal.h>
